import type { CanvasBounds } from "@anvilkit/canvas-core";
import {
	ellipseEntry,
	filledPathEntry,
	frameEntry,
	LINE_DEFAULT_SIZE,
	polygonEntry,
	rectEntry,
	SHAPE_DEFAULT_SIZE,
	starEntry,
	stickerEntry,
	strokedLineEntry,
	strokedPathEntry,
} from "./catalog-builders.js";
import type { CanvasElementEntry } from "./element-entry.js";

/**
 * The four non-icon categories of the default catalog (`cp3-002`): `shape`,
 * `line`, `frame`, `sticker`.
 *
 * ALL GEOMETRY HERE IS ORIGINAL TO THIS PACKAGE.
 *
 * Nothing in this module is transcribed from a third party, which is why every
 * entry carries this package's own `MIT` and points its `upstreamUrl` at this
 * repository. That is a deliberate split from `catalog-icons.ts`: an icon set
 * is worth vendoring because drawing 300 recognisable pictograms by hand is not
 * a good use of anyone's time, whereas a rectangle, a hexagon and a speech
 * bubble are geometry, and vendoring them would take on a notice obligation for
 * something a formula produces.
 *
 * TWO CONSTRUCTION RULES THAT ARE NOT PREFERENCES.
 *
 * 1. **Parametric where `canvas-core` is already parametric.** A pentagon is a
 *    `polygon` node with `sides: 5`, not a path of five hand-typed vertices —
 *    so it stays a regular pentagon at any aspect ratio, the inspector can edit
 *    its side count, and the thumbnail is drawn from
 *    `computePolygonVertices`, the same function the SVG serializer uses.
 *    A path is used only where no primitive expresses the shape.
 * 2. **Non-zero winding, always.** Neither renderer emits `fill-rule`
 *    (see `catalog-icons.ts`), so a shape with a hole — `ring`,
 *    `square-outline` — draws its inner contour in the OPPOSITE direction to
 *    the outer one, which is what makes non-zero cancel to a hole. A shape
 *    whose subpaths must merge instead — `cloud`, `thought-bubble` — draws them
 *    all in the SAME direction, which is what makes non-zero union them.
 *
 *    Winding is not verifiable from a unit test here: `Path2D` does not exist
 *    in this package's jsdom environment, which is why the renderer itself
 *    guards on `typeof Path2D !== "function"`. It was verified instead by
 *    rasterising each of these fourteen shapes in a real browser and probing
 *    `CanvasRenderingContext2D.isPointInPath` — the same non-zero rule Konva
 *    and the SVG exporter use — at points inside and inside-the-hole. 38
 *    probes, all correct; the run is recorded in `cp3-002`'s execution record.
 *    What the spec CAN check, and does, is that every path is parseable,
 *    encloses real area, and survives `serializePageToSvg` unwarned.
 */

const MIT = "MIT";

/** Every shape/line/frame/sticker is original work under this package's licence. */
const OWN_WORK = {
	license: MIT,
	upstreamUrl: "https://github.com/ancyloce/anvilkit-studio",
} as const;

const SQUARE_BOX: CanvasBounds = { width: 100, height: 100 };
const WIDE_BOX: CanvasBounds = { width: 200, height: 100 };
const WIDE_SIZE: CanvasBounds = { width: 320, height: 160 };
const H_LINE_BOX: CanvasBounds = { width: 240, height: 48 };
const V_LINE_BOX: CanvasBounds = { width: 48, height: 240 };
const V_LINE_SIZE: CanvasBounds = { width: 48, height: 240 };
const DIAG_BOX: CanvasBounds = { width: 240, height: 240 };
const DIAG_SIZE: CanvasBounds = { width: 240, height: 240 };
const STICKER_BOX: CanvasBounds = { width: 200, height: 200 };
const STICKER_SIZE: CanvasBounds = { width: 240, height: 240 };
const LINE_WEIGHT = 4;

// --- shapes ------------------------------------------------------------------

/**
 * Bounds-sized shapes: `rect`, `ellipse`, `polygon`, `star`.
 *
 * The star ratios are chosen so the set reads as distinct silhouettes rather
 * than one star at five sizes: 0.18 is a four-pointed sparkle, 0.38-0.55 are
 * conventional stars, and 0.75-0.84 are sunbursts whose points are shallow
 * enough to read as a scalloped disc.
 */
const PRIMITIVE_SHAPES: readonly CanvasElementEntry[] = [
	rectEntry(
		{
			...OWN_WORK,
			id: "shape-rectangle",
			name: "Rectangle",
			category: "shape",
			tags: ["shape", "basic"],
			keywords: ["rectangle", "box", "block", "oblong", "banner", "panel"],
		},
		{},
		{ width: 320, height: 200 },
	),
	rectEntry(
		{
			...OWN_WORK,
			id: "shape-square",
			name: "Square",
			category: "shape",
			tags: ["shape", "basic"],
			keywords: ["square", "box", "block", "tile", "quad"],
		},
		{},
		SHAPE_DEFAULT_SIZE,
	),
	rectEntry(
		{
			...OWN_WORK,
			id: "shape-rounded-rectangle",
			name: "Rounded rectangle",
			category: "shape",
			tags: ["shape", "basic"],
			keywords: [
				"rounded rectangle",
				"card",
				"panel",
				"button",
				"box",
				"radius",
			],
		},
		{ radius: 32 },
		{ width: 320, height: 200 },
	),
	rectEntry(
		{
			...OWN_WORK,
			id: "shape-rounded-square",
			name: "Rounded square",
			category: "shape",
			tags: ["shape", "basic"],
			keywords: ["rounded square", "squircle", "tile", "app icon", "box"],
		},
		{ radius: 40 },
		SHAPE_DEFAULT_SIZE,
	),
	rectEntry(
		{
			...OWN_WORK,
			id: "shape-pill",
			name: "Pill",
			category: "shape",
			tags: ["shape", "basic"],
			keywords: [
				"pill",
				"capsule",
				"chip",
				"tag",
				"badge",
				"lozenge",
				"button",
			],
		},
		{ radius: 100 },
		{ width: 320, height: 120 },
	),
	ellipseEntry(
		{
			...OWN_WORK,
			id: "shape-circle",
			name: "Circle",
			category: "shape",
			tags: ["shape", "basic"],
			keywords: ["circle", "round", "dot", "disc", "ball", "bullet"],
		},
		SHAPE_DEFAULT_SIZE,
	),
	ellipseEntry(
		{
			...OWN_WORK,
			id: "shape-ellipse",
			name: "Ellipse",
			category: "shape",
			tags: ["shape", "basic"],
			keywords: ["ellipse", "oval", "round", "egg", "capsule"],
		},
		{ width: 320, height: 200 },
	),
	polygonEntry(
		{
			...OWN_WORK,
			id: "shape-triangle",
			name: "Triangle",
			category: "shape",
			tags: ["shape", "polygon"],
			keywords: ["triangle", "three", "delta", "cone", "arrow", "pyramid"],
		},
		{ sides: 3 },
		SHAPE_DEFAULT_SIZE,
	),
	polygonEntry(
		{
			...OWN_WORK,
			id: "shape-diamond",
			name: "Diamond",
			category: "shape",
			tags: ["shape", "polygon"],
			keywords: ["diamond", "rhombus", "kite", "gem", "lozenge", "four"],
		},
		{ sides: 4 },
		SHAPE_DEFAULT_SIZE,
	),
	polygonEntry(
		{
			...OWN_WORK,
			id: "shape-pentagon",
			name: "Pentagon",
			category: "shape",
			tags: ["shape", "polygon"],
			keywords: ["pentagon", "five", "polygon", "badge"],
		},
		{ sides: 5 },
		SHAPE_DEFAULT_SIZE,
	),
	polygonEntry(
		{
			...OWN_WORK,
			id: "shape-hexagon",
			name: "Hexagon",
			category: "shape",
			tags: ["shape", "polygon"],
			keywords: ["hexagon", "six", "polygon", "honeycomb", "hex", "cell"],
		},
		{ sides: 6 },
		SHAPE_DEFAULT_SIZE,
	),
	polygonEntry(
		{
			...OWN_WORK,
			id: "shape-heptagon",
			name: "Heptagon",
			category: "shape",
			tags: ["shape", "polygon"],
			keywords: ["heptagon", "seven", "polygon", "septagon"],
		},
		{ sides: 7 },
		SHAPE_DEFAULT_SIZE,
	),
	polygonEntry(
		{
			...OWN_WORK,
			id: "shape-octagon",
			name: "Octagon",
			category: "shape",
			tags: ["shape", "polygon"],
			keywords: ["octagon", "eight", "polygon", "stop sign", "stop"],
		},
		{ sides: 8 },
		SHAPE_DEFAULT_SIZE,
	),
	polygonEntry(
		{
			...OWN_WORK,
			id: "shape-nonagon",
			name: "Nonagon",
			category: "shape",
			tags: ["shape", "polygon"],
			keywords: ["nonagon", "nine", "polygon", "enneagon"],
		},
		{ sides: 9 },
		SHAPE_DEFAULT_SIZE,
	),
	polygonEntry(
		{
			...OWN_WORK,
			id: "shape-decagon",
			name: "Decagon",
			category: "shape",
			tags: ["shape", "polygon"],
			keywords: ["decagon", "ten", "polygon", "medal", "seal"],
		},
		{ sides: 10 },
		SHAPE_DEFAULT_SIZE,
	),
	polygonEntry(
		{
			...OWN_WORK,
			id: "shape-dodecagon",
			name: "Dodecagon",
			category: "shape",
			tags: ["shape", "polygon"],
			keywords: ["dodecagon", "twelve", "polygon", "coin", "disc"],
		},
		{ sides: 12 },
		SHAPE_DEFAULT_SIZE,
	),
	starEntry(
		{
			...OWN_WORK,
			id: "shape-sparkle",
			name: "Sparkle",
			category: "shape",
			tags: ["shape", "star"],
			keywords: ["sparkle", "twinkle", "shine", "glint", "magic", "star", "ai"],
		},
		{ points: 4, innerRadiusRatio: 0.18 },
		SHAPE_DEFAULT_SIZE,
	),
	starEntry(
		{
			...OWN_WORK,
			id: "shape-star-4",
			name: "Four-point star",
			category: "shape",
			tags: ["shape", "star"],
			keywords: ["star", "four point", "compass", "shine", "cross", "sparkle"],
		},
		{ points: 4, innerRadiusRatio: 0.38 },
		SHAPE_DEFAULT_SIZE,
	),
	starEntry(
		{
			...OWN_WORK,
			id: "shape-star-5",
			name: "Five-point star",
			category: "shape",
			tags: ["shape", "star"],
			keywords: [
				"star",
				"five point",
				"rating",
				"favourite",
				"favorite",
				"award",
			],
		},
		{ points: 5, innerRadiusRatio: 0.45 },
		SHAPE_DEFAULT_SIZE,
	),
	starEntry(
		{
			...OWN_WORK,
			id: "shape-star-6",
			name: "Six-point star",
			category: "shape",
			tags: ["shape", "star"],
			keywords: ["star", "six point", "hexagram", "snowflake", "sheriff"],
		},
		{ points: 6, innerRadiusRatio: 0.55 },
		SHAPE_DEFAULT_SIZE,
	),
	starEntry(
		{
			...OWN_WORK,
			id: "shape-star-8",
			name: "Eight-point star",
			category: "shape",
			tags: ["shape", "star"],
			keywords: ["star", "eight point", "compass rose", "shine", "burst"],
		},
		{ points: 8, innerRadiusRatio: 0.6 },
		SHAPE_DEFAULT_SIZE,
	),
	starEntry(
		{
			...OWN_WORK,
			id: "shape-burst-12",
			name: "Sunburst",
			category: "shape",
			tags: ["shape", "star"],
			keywords: [
				"sunburst",
				"burst",
				"badge",
				"sale",
				"flash",
				"star",
				"sticker",
			],
		},
		{ points: 12, innerRadiusRatio: 0.75 },
		SHAPE_DEFAULT_SIZE,
	),
	starEntry(
		{
			...OWN_WORK,
			id: "shape-burst-20",
			name: "Scalloped disc",
			category: "shape",
			tags: ["shape", "star"],
			keywords: [
				"scalloped",
				"burst",
				"flower",
				"seal",
				"stamp",
				"badge",
				"disc",
			],
		},
		{ points: 20, innerRadiusRatio: 0.84 },
		SHAPE_DEFAULT_SIZE,
	),
];

/** Path-drawn shapes: everything no `canvas-core` primitive expresses. */
const PATH_SHAPES: readonly CanvasElementEntry[] = [
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-triangle-right",
			name: "Right triangle",
			category: "shape",
			tags: ["shape", "arrow"],
			keywords: [
				"triangle right",
				"play",
				"caret",
				"pointer",
				"wedge",
				"start",
			],
		},
		{ d: "M0 0L100 50L0 100Z", viewBox: SQUARE_BOX },
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-arrow-right",
			name: "Arrow right",
			category: "shape",
			tags: ["shape", "arrow"],
			keywords: [
				"arrow right",
				"next",
				"forward",
				"east",
				"direction",
				"block arrow",
			],
		},
		{ d: "M0 32H58V0L100 50L58 100V68H0Z", viewBox: SQUARE_BOX },
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-arrow-left",
			name: "Arrow left",
			category: "shape",
			tags: ["shape", "arrow"],
			keywords: [
				"arrow left",
				"back",
				"previous",
				"west",
				"direction",
				"block arrow",
			],
		},
		{ d: "M100 32H42V0L0 50L42 100V68H100Z", viewBox: SQUARE_BOX },
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-arrow-up",
			name: "Arrow up",
			category: "shape",
			tags: ["shape", "arrow"],
			keywords: [
				"arrow up",
				"north",
				"rise",
				"increase",
				"direction",
				"block arrow",
			],
		},
		{ d: "M32 100V42H0L50 0L100 42H68V100Z", viewBox: SQUARE_BOX },
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-arrow-down",
			name: "Arrow down",
			category: "shape",
			tags: ["shape", "arrow"],
			keywords: [
				"arrow down",
				"south",
				"fall",
				"decrease",
				"direction",
				"block arrow",
			],
		},
		{ d: "M32 0V58H0L50 100L100 58H68V0Z", viewBox: SQUARE_BOX },
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-arrow-double",
			name: "Double arrow",
			category: "shape",
			tags: ["shape", "arrow"],
			keywords: [
				"double arrow",
				"swap",
				"exchange",
				"both ways",
				"sync",
				"transfer",
			],
		},
		{ d: "M0 50L28 20V38H72V20L100 50L72 80V62H28V80Z", viewBox: SQUARE_BOX },
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-chevron",
			name: "Chevron",
			category: "shape",
			tags: ["shape", "arrow"],
			keywords: ["chevron", "arrow head", "next", "angle", "bracket", "point"],
		},
		{ d: "M8 0L58 50L8 100H42L92 50L42 0Z", viewBox: SQUARE_BOX },
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-cross",
			name: "Cross",
			category: "shape",
			tags: ["shape", "basic"],
			keywords: ["cross", "plus", "add", "medical", "first aid", "health"],
		},
		{ d: "M35 0H65V35H100V65H65V100H35V65H0V35H35Z", viewBox: SQUARE_BOX },
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-x-cross",
			name: "X cross",
			category: "shape",
			tags: ["shape", "basic"],
			keywords: [
				"x",
				"cross",
				"close",
				"cancel",
				"multiply",
				"times",
				"saltire",
			],
		},
		{
			d: "M29.3 8L50 28.7L70.7 8L92 29.3L71.3 50L92 70.7L70.7 92L50 71.3L29.3 92L8 70.7L28.7 50L8 29.3Z",
			viewBox: SQUARE_BOX,
		},
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-parallelogram",
			name: "Parallelogram",
			category: "shape",
			tags: ["shape", "polygon"],
			keywords: ["parallelogram", "slant", "skew", "rhomboid", "italic box"],
		},
		{ d: "M25 0H100L75 100H0Z", viewBox: SQUARE_BOX },
		{ width: 320, height: 200 },
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-trapezoid",
			name: "Trapezoid",
			category: "shape",
			tags: ["shape", "polygon"],
			keywords: ["trapezoid", "trapezium", "taper", "wedge", "funnel"],
		},
		{ d: "M25 0H75L100 100H0Z", viewBox: SQUARE_BOX },
		{ width: 320, height: 200 },
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-heart",
			name: "Heart",
			category: "shape",
			tags: ["shape", "social"],
			keywords: [
				"heart",
				"love",
				"like",
				"favourite",
				"favorite",
				"valentine",
				"romance",
			],
		},
		{
			d: "M50 96C50 96 6 68 6 36C6 18 20 6 34 6C42 6 48 11 50 16C52 11 58 6 66 6C80 6 94 18 94 36C94 68 50 96 50 96Z",
			viewBox: SQUARE_BOX,
		},
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-shield",
			name: "Shield",
			category: "shape",
			tags: ["shape", "security"],
			keywords: [
				"shield",
				"badge",
				"crest",
				"protection",
				"guard",
				"secure",
				"safety",
			],
		},
		{
			d: "M50 2L96 18V52C96 76 76 92 50 98C24 92 4 76 4 52V18Z",
			viewBox: SQUARE_BOX,
		},
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-speech-round",
			name: "Speech bubble",
			category: "shape",
			tags: ["shape", "communication"],
			keywords: [
				"speech bubble",
				"chat",
				"comment",
				"message",
				"talk",
				"quote",
				"callout",
			],
		},
		{
			d: "M18 0H82A18 18 0 0 1 100 18V54A18 18 0 0 1 82 72H46L20 96V72H18A18 18 0 0 1 0 54V18A18 18 0 0 1 18 0Z",
			viewBox: SQUARE_BOX,
		},
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-speech-square",
			name: "Square speech bubble",
			category: "shape",
			tags: ["shape", "communication"],
			keywords: [
				"speech bubble",
				"chat",
				"comment",
				"message",
				"callout",
				"box",
				"tooltip",
			],
		},
		{ d: "M0 0H100V72H46L20 96V72H0Z", viewBox: SQUARE_BOX },
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-thought-bubble",
			name: "Thought bubble",
			category: "shape",
			tags: ["shape", "communication"],
			keywords: [
				"thought bubble",
				"think",
				"idea",
				"dream",
				"cloud",
				"comment",
				"imagine",
			],
		},
		{
			d: "M6 34A44 28 0 0 1 94 34A44 28 0 0 1 6 34ZM26 70A10 10 0 0 1 46 70A10 10 0 0 1 26 70ZM10 91A7 7 0 0 1 24 91A7 7 0 0 1 10 91Z",
			viewBox: SQUARE_BOX,
		},
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-cloud",
			name: "Cloud",
			category: "shape",
			tags: ["shape", "weather"],
			keywords: [
				"cloud",
				"weather",
				"sky",
				"overcast",
				"storage",
				"puff",
				"fluffy",
			],
		},
		{
			d: "M26 84A26 26 0 0 1 26 32A28 28 0 0 1 76 24A22 22 0 0 1 92 46A21 21 0 0 1 86 84Z",
			viewBox: SQUARE_BOX,
		},
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-teardrop",
			name: "Teardrop",
			category: "shape",
			tags: ["shape", "nature"],
			keywords: [
				"teardrop",
				"drop",
				"droplet",
				"water",
				"rain",
				"liquid",
				"tear",
			],
		},
		{
			d: "M50 2C68 26 92 44 92 62A42 42 0 0 1 8 62C8 44 32 26 50 2Z",
			viewBox: SQUARE_BOX,
		},
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-crescent",
			name: "Crescent",
			category: "shape",
			tags: ["shape", "nature"],
			keywords: ["crescent", "moon", "night", "lunar", "sliver", "dark mode"],
		},
		{ d: "M50 4A46 46 0 1 0 50 96A58 58 0 0 1 50 4Z", viewBox: SQUARE_BOX },
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-semicircle",
			name: "Half circle",
			category: "shape",
			tags: ["shape", "basic"],
			keywords: [
				"semicircle",
				"half circle",
				"dome",
				"arch",
				"hemisphere",
				"half",
			],
		},
		{ d: "M0 100A50 100 0 0 1 100 100Z", viewBox: SQUARE_BOX },
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-quarter-circle",
			name: "Quarter circle",
			category: "shape",
			tags: ["shape", "basic"],
			keywords: [
				"quarter circle",
				"quadrant",
				"pie slice",
				"corner",
				"fan",
				"wedge",
			],
		},
		{ d: "M0 100V0A100 100 0 0 1 100 100Z", viewBox: SQUARE_BOX },
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-arch",
			name: "Arch",
			category: "shape",
			tags: ["shape", "basic"],
			keywords: [
				"arch",
				"archway",
				"dome",
				"window",
				"portal",
				"tombstone",
				"gate",
			],
		},
		{ d: "M0 100V50A50 50 0 0 1 100 50V100Z", viewBox: SQUARE_BOX },
		{ width: 200, height: 280 },
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-banner",
			name: "Banner",
			category: "shape",
			tags: ["shape", "celebration"],
			keywords: [
				"banner",
				"ribbon",
				"flag",
				"header",
				"label",
				"streamer",
				"title",
			],
		},
		{ d: "M0 20H200L176 50L200 80H0L24 50Z", viewBox: WIDE_BOX },
		WIDE_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-ribbon",
			name: "Ribbon",
			category: "shape",
			tags: ["shape", "celebration"],
			keywords: [
				"ribbon",
				"bookmark",
				"award",
				"pennant",
				"tag",
				"marker",
				"prize",
			],
		},
		{ d: "M18 0H82V100L50 76L18 100Z", viewBox: SQUARE_BOX },
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-blob",
			name: "Blob",
			category: "shape",
			tags: ["shape", "organic"],
			keywords: [
				"blob",
				"organic",
				"splat",
				"amoeba",
				"abstract",
				"freeform",
				"bubble",
			],
		},
		{
			d: "M62 6C82 10 98 26 96 48C94 70 78 92 54 96C30 100 8 84 5 60C2 36 14 14 34 7C45 3 52 4 62 6Z",
			viewBox: SQUARE_BOX,
		},
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-lightning",
			name: "Lightning bolt",
			category: "shape",
			tags: ["shape", "weather"],
			keywords: [
				"lightning",
				"bolt",
				"flash",
				"energy",
				"power",
				"zap",
				"storm",
				"electric",
			],
		},
		{ d: "M56 2L14 58H44L38 98L86 40H54Z", viewBox: SQUARE_BOX },
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-location-pin",
			name: "Location pin",
			category: "shape",
			tags: ["shape", "geography"],
			keywords: [
				"location pin",
				"map pin",
				"marker",
				"place",
				"geo",
				"address",
				"here",
			],
		},
		{
			d: "M50 2A34 34 0 0 1 84 36C84 60 50 98 50 98C50 98 16 60 16 36A34 34 0 0 1 50 2Z",
			viewBox: SQUARE_BOX,
		},
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-wave-block",
			name: "Wave block",
			category: "shape",
			tags: ["shape", "organic"],
			keywords: [
				"wave block",
				"wave",
				"section divider",
				"hill",
				"curve",
				"swoosh",
				"footer",
			],
		},
		{
			d: "M0 30C34 4 62 52 100 30C138 8 166 52 200 30V100H0Z",
			viewBox: WIDE_BOX,
		},
		WIDE_SIZE,
	),
	// The two hole-bearing shapes. Outer contour clockwise, inner contour
	// counter-clockwise: non-zero winding then cancels to a hole with no
	// `fill-rule` involved. Reverse either one and the shape fills solid.
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-ring",
			name: "Ring",
			category: "shape",
			tags: ["shape", "outline"],
			keywords: [
				"ring",
				"donut",
				"doughnut",
				"annulus",
				"circle outline",
				"loop",
				"hoop",
			],
		},
		{
			d: "M2 50A48 48 0 0 1 98 50A48 48 0 0 1 2 50ZM26 50A24 24 0 0 0 74 50A24 24 0 0 0 26 50Z",
			viewBox: SQUARE_BOX,
		},
		SHAPE_DEFAULT_SIZE,
	),
	filledPathEntry(
		{
			...OWN_WORK,
			id: "shape-square-outline",
			name: "Square outline",
			category: "shape",
			tags: ["shape", "outline"],
			keywords: [
				"square outline",
				"border",
				"frame",
				"box outline",
				"hollow",
				"window",
			],
		},
		{ d: "M0 0H100V100H0ZM12 12V88H88V12Z", viewBox: SQUARE_BOX },
		SHAPE_DEFAULT_SIZE,
	),
];

// --- lines -------------------------------------------------------------------

/**
 * Rules and connectors.
 *
 * The plain rules are real `line` nodes so the arrowheads (`arrowStart` /
 * `arrowEnd`, FR-075) and the dash array are the IR's own fields rather than
 * geometry baked into a path — an inserted arrow can therefore have its head
 * turned off in the inspector. Everything curved is a stroked `path`, because
 * a `line` node is two points by definition.
 */
const LINES: readonly CanvasElementEntry[] = [
	strokedLineEntry(
		{
			...OWN_WORK,
			id: "line-horizontal",
			name: "Horizontal rule",
			category: "line",
			tags: ["line", "divider"],
			keywords: [
				"horizontal line",
				"rule",
				"divider",
				"separator",
				"hr",
				"underline",
				"straight",
			],
		},
		{ points: [0, 24, 240, 24], box: H_LINE_BOX, strokeWidth: LINE_WEIGHT },
		LINE_DEFAULT_SIZE,
	),
	strokedLineEntry(
		{
			...OWN_WORK,
			id: "line-horizontal-thick",
			name: "Thick rule",
			category: "line",
			tags: ["line", "divider"],
			keywords: [
				"thick line",
				"heavy rule",
				"bar",
				"divider",
				"separator",
				"bold line",
			],
		},
		{ points: [0, 24, 240, 24], box: H_LINE_BOX, strokeWidth: 12 },
		LINE_DEFAULT_SIZE,
	),
	strokedLineEntry(
		{
			...OWN_WORK,
			id: "line-vertical",
			name: "Vertical rule",
			category: "line",
			tags: ["line", "divider"],
			keywords: [
				"vertical line",
				"rule",
				"divider",
				"separator",
				"column",
				"pipe",
				"straight",
			],
		},
		{ points: [24, 0, 24, 240], box: V_LINE_BOX, strokeWidth: LINE_WEIGHT },
		V_LINE_SIZE,
	),
	strokedLineEntry(
		{
			...OWN_WORK,
			id: "line-diagonal",
			name: "Diagonal rule",
			category: "line",
			tags: ["line", "divider"],
			keywords: [
				"diagonal line",
				"slash",
				"oblique",
				"slant",
				"strike",
				"cross out",
			],
		},
		{ points: [0, 240, 240, 0], box: DIAG_BOX, strokeWidth: LINE_WEIGHT },
		DIAG_SIZE,
	),
	strokedLineEntry(
		{
			...OWN_WORK,
			id: "line-dashed",
			name: "Dashed rule",
			category: "line",
			tags: ["line", "divider"],
			keywords: [
				"dashed line",
				"dashes",
				"broken line",
				"divider",
				"cut here",
				"separator",
			],
		},
		{
			points: [0, 24, 240, 24],
			box: H_LINE_BOX,
			strokeWidth: LINE_WEIGHT,
			strokeDash: [16, 12],
		},
		LINE_DEFAULT_SIZE,
	),
	strokedLineEntry(
		{
			...OWN_WORK,
			id: "line-dotted",
			name: "Dotted rule",
			category: "line",
			tags: ["line", "divider"],
			keywords: [
				"dotted line",
				"dots",
				"leader",
				"divider",
				"separator",
				"pointille",
			],
		},
		{
			points: [0, 24, 240, 24],
			box: H_LINE_BOX,
			strokeWidth: 5,
			strokeDash: [0.1, 14],
		},
		LINE_DEFAULT_SIZE,
	),
	strokedLineEntry(
		{
			...OWN_WORK,
			id: "line-arrow-right",
			name: "Arrow line",
			category: "line",
			tags: ["line", "arrow"],
			keywords: [
				"arrow line",
				"pointer",
				"connector",
				"direction",
				"leads to",
				"next",
			],
		},
		{
			points: [0, 24, 240, 24],
			box: H_LINE_BOX,
			strokeWidth: LINE_WEIGHT,
			arrowEnd: "arrow",
		},
		LINE_DEFAULT_SIZE,
	),
	strokedLineEntry(
		{
			...OWN_WORK,
			id: "line-arrow-left",
			name: "Reverse arrow line",
			category: "line",
			tags: ["line", "arrow"],
			keywords: [
				"arrow line",
				"back",
				"reverse",
				"connector",
				"direction",
				"previous",
			],
		},
		{
			points: [0, 24, 240, 24],
			box: H_LINE_BOX,
			strokeWidth: LINE_WEIGHT,
			arrowStart: "arrow",
		},
		LINE_DEFAULT_SIZE,
	),
	strokedLineEntry(
		{
			...OWN_WORK,
			id: "line-arrow-both",
			name: "Double-headed arrow",
			category: "line",
			tags: ["line", "arrow"],
			keywords: [
				"double arrow",
				"both ways",
				"measure",
				"dimension",
				"span",
				"width",
				"swap",
			],
		},
		{
			points: [0, 24, 240, 24],
			box: H_LINE_BOX,
			strokeWidth: LINE_WEIGHT,
			arrowStart: "arrow",
			arrowEnd: "arrow",
		},
		LINE_DEFAULT_SIZE,
	),
	strokedPathEntry(
		{
			...OWN_WORK,
			id: "line-double-rule",
			name: "Double rule",
			category: "line",
			tags: ["line", "divider"],
			keywords: [
				"double rule",
				"two lines",
				"divider",
				"separator",
				"border",
				"railroad",
			],
		},
		{ d: "M0 16H240M0 32H240", viewBox: H_LINE_BOX, strokeWidth: LINE_WEIGHT },
		LINE_DEFAULT_SIZE,
	),
	strokedPathEntry(
		{
			...OWN_WORK,
			id: "line-zigzag",
			name: "Zigzag",
			category: "line",
			tags: ["line", "decorative"],
			keywords: [
				"zigzag",
				"chevron line",
				"saw",
				"jagged",
				"lightning line",
				"sharp wave",
			],
		},
		{
			d: "M0 36L30 12L60 36L90 12L120 36L150 12L180 36L210 12L240 36",
			viewBox: H_LINE_BOX,
			strokeWidth: LINE_WEIGHT,
		},
		LINE_DEFAULT_SIZE,
	),
	strokedPathEntry(
		{
			...OWN_WORK,
			id: "line-wave",
			name: "Wave",
			category: "line",
			tags: ["line", "decorative"],
			keywords: [
				"wave",
				"squiggle",
				"wavy line",
				"curvy",
				"underline",
				"ripple",
				"sine",
			],
		},
		{
			d: "M0 24C15 4 45 4 60 24C75 44 105 44 120 24C135 4 165 4 180 24C195 44 225 44 240 24",
			viewBox: H_LINE_BOX,
			strokeWidth: LINE_WEIGHT,
		},
		LINE_DEFAULT_SIZE,
	),
	strokedPathEntry(
		{
			...OWN_WORK,
			id: "line-wave-tight",
			name: "Tight wave",
			category: "line",
			tags: ["line", "decorative"],
			keywords: [
				"tight wave",
				"squiggle",
				"ripple",
				"vibration",
				"spelling underline",
				"zigzag",
			],
		},
		{
			d: "M0 24C8 8 22 8 30 24C38 40 52 40 60 24C68 8 82 8 90 24C98 40 112 40 120 24C128 8 142 8 150 24C158 40 172 40 180 24C188 8 202 8 210 24C218 40 232 40 240 24",
			viewBox: H_LINE_BOX,
			strokeWidth: LINE_WEIGHT,
		},
		LINE_DEFAULT_SIZE,
	),
	strokedPathEntry(
		{
			...OWN_WORK,
			id: "line-loops",
			name: "Loops",
			category: "line",
			tags: ["line", "decorative"],
			keywords: [
				"loops",
				"coil",
				"spring",
				"curls",
				"spiral line",
				"doodle",
				"chain",
			],
		},
		{
			d: "M8 24A16 16 0 1 1 40 24A16 16 0 1 1 72 24A16 16 0 1 1 104 24A16 16 0 1 1 136 24A16 16 0 1 1 168 24A16 16 0 1 1 200 24A16 16 0 1 1 232 24",
			viewBox: H_LINE_BOX,
			strokeWidth: LINE_WEIGHT,
		},
		LINE_DEFAULT_SIZE,
	),
	strokedPathEntry(
		{
			...OWN_WORK,
			id: "line-scribble",
			name: "Scribble",
			category: "line",
			tags: ["line", "decorative"],
			keywords: [
				"scribble",
				"sketch",
				"hand drawn",
				"doodle",
				"rough line",
				"marker",
				"swash",
			],
		},
		{
			d: "M0 34C24 6 48 44 72 16C96 -12 120 40 144 14C168 -12 192 42 216 18C226 8 234 24 240 30",
			viewBox: H_LINE_BOX,
			strokeWidth: LINE_WEIGHT,
		},
		LINE_DEFAULT_SIZE,
	),
	strokedPathEntry(
		{
			...OWN_WORK,
			id: "line-swash",
			name: "Swash underline",
			category: "line",
			tags: ["line", "decorative"],
			keywords: [
				"swash",
				"underline",
				"highlight",
				"brush stroke",
				"emphasis",
				"flourish",
			],
		},
		{
			d: "M2 34C40 12 88 40 130 20C168 2 210 26 238 14",
			viewBox: H_LINE_BOX,
			strokeWidth: 8,
		},
		LINE_DEFAULT_SIZE,
	),
	strokedPathEntry(
		{
			...OWN_WORK,
			id: "line-bracket-left",
			name: "Left bracket",
			category: "line",
			tags: ["line", "decorative"],
			keywords: [
				"left bracket",
				"brace",
				"grouping",
				"annotation",
				"callout",
				"span",
			],
		},
		{ d: "M40 4H12V236H40", viewBox: V_LINE_BOX, strokeWidth: LINE_WEIGHT },
		V_LINE_SIZE,
	),
	strokedPathEntry(
		{
			...OWN_WORK,
			id: "line-bracket-right",
			name: "Right bracket",
			category: "line",
			tags: ["line", "decorative"],
			keywords: [
				"right bracket",
				"brace",
				"grouping",
				"annotation",
				"callout",
				"span",
			],
		},
		{ d: "M8 4H36V236H8", viewBox: V_LINE_BOX, strokeWidth: LINE_WEIGHT },
		V_LINE_SIZE,
	),
	strokedPathEntry(
		{
			...OWN_WORK,
			id: "line-brace",
			name: "Curly brace",
			category: "line",
			tags: ["line", "decorative"],
			keywords: [
				"curly brace",
				"brace",
				"bracket",
				"grouping",
				"annotation",
				"span",
				"curly",
			],
		},
		{
			d: "M38 4C22 4 30 108 8 120C30 132 22 236 38 236",
			viewBox: V_LINE_BOX,
			strokeWidth: LINE_WEIGHT,
		},
		V_LINE_SIZE,
	),
	strokedPathEntry(
		{
			...OWN_WORK,
			id: "line-arc",
			name: "Arc",
			category: "line",
			tags: ["line", "connector"],
			keywords: ["arc", "curve", "bow", "bend", "quarter circle line", "sweep"],
		},
		{
			d: "M4 236A232 232 0 0 1 236 4",
			viewBox: DIAG_BOX,
			strokeWidth: LINE_WEIGHT,
		},
		DIAG_SIZE,
	),
	strokedPathEntry(
		{
			...OWN_WORK,
			id: "line-s-curve",
			name: "S curve",
			category: "line",
			tags: ["line", "connector"],
			keywords: [
				"s curve",
				"bezier",
				"flow",
				"connector",
				"sigmoid",
				"path",
				"snake",
			],
		},
		{
			d: "M4 236C4 140 236 100 236 4",
			viewBox: DIAG_BOX,
			strokeWidth: LINE_WEIGHT,
		},
		DIAG_SIZE,
	),
	strokedPathEntry(
		{
			...OWN_WORK,
			id: "line-elbow",
			name: "Elbow connector",
			category: "line",
			tags: ["line", "connector"],
			keywords: [
				"elbow",
				"corner",
				"right angle",
				"connector",
				"flowchart",
				"bend",
				"l shape",
			],
		},
		{
			d: "M4 4V180A56 56 0 0 0 60 236H236",
			viewBox: DIAG_BOX,
			strokeWidth: LINE_WEIGHT,
		},
		DIAG_SIZE,
	),
	strokedPathEntry(
		{
			...OWN_WORK,
			id: "line-steps",
			name: "Step connector",
			category: "line",
			tags: ["line", "connector"],
			keywords: [
				"steps",
				"staircase",
				"stepped line",
				"flowchart",
				"connector",
				"ladder",
			],
		},
		{
			d: "M4 236V160H84V84H164V4",
			viewBox: DIAG_BOX,
			strokeWidth: LINE_WEIGHT,
		},
		DIAG_SIZE,
	),
	strokedPathEntry(
		{
			...OWN_WORK,
			id: "line-arrow-curved",
			name: "Curved arrow",
			category: "line",
			tags: ["line", "arrow"],
			keywords: [
				"curved arrow",
				"swoosh arrow",
				"pointer",
				"annotation",
				"look here",
				"callout",
			],
		},
		{
			d: "M8 148C60 40 170 20 228 44",
			viewBox: WIDE_BOX,
			strokeWidth: LINE_WEIGHT,
			arrowEnd: "arrow",
		},
		WIDE_SIZE,
	),
	strokedPathEntry(
		{
			...OWN_WORK,
			id: "line-arrow-elbow",
			name: "Elbow arrow",
			category: "line",
			tags: ["line", "arrow"],
			keywords: [
				"elbow arrow",
				"right angle arrow",
				"flowchart",
				"connector",
				"routes to",
			],
		},
		{
			d: "M8 20H150A26 26 0 0 1 176 46V90",
			viewBox: WIDE_BOX,
			strokeWidth: LINE_WEIGHT,
			arrowEnd: "arrow",
		},
		WIDE_SIZE,
	),
];

// --- frames ------------------------------------------------------------------

/**
 * Image wells.
 *
 * Every one is a `frame` with `clip: true`, a neutral background and
 * `placeholder: { kind: "image" }` and NO `assetId` — see `frameEntry`. The
 * shaped ones set the frame's `shape` (ADR 0008 decision 2), which the single
 * `resolveFrameClipShape` then hands to both the Konva `clipFunc` and the SVG
 * `<clipPath>`, so a shaped well looks the same on the stage and in an export.
 */
const FRAMES: readonly CanvasElementEntry[] = [
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-square",
			name: "Square frame",
			category: "frame",
			tags: ["frame", "photo"],
			keywords: [
				"square frame",
				"image",
				"photo",
				"picture",
				"placeholder",
				"1:1",
				"well",
			],
		},
		{},
		{ width: 400, height: 400 },
	),
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-portrait",
			name: "Portrait frame",
			category: "frame",
			tags: ["frame", "photo"],
			keywords: [
				"portrait frame",
				"image",
				"photo",
				"picture",
				"3:4",
				"tall",
				"vertical",
			],
		},
		{},
		{ width: 300, height: 400 },
	),
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-landscape",
			name: "Landscape frame",
			category: "frame",
			tags: ["frame", "photo"],
			keywords: [
				"landscape frame",
				"image",
				"photo",
				"picture",
				"4:3",
				"wide",
				"horizontal",
			],
		},
		{},
		{ width: 400, height: 300 },
	),
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-widescreen",
			name: "Widescreen frame",
			category: "frame",
			tags: ["frame", "photo"],
			keywords: [
				"widescreen frame",
				"16:9",
				"video",
				"cover",
				"banner",
				"hero",
				"cinema",
			],
		},
		{},
		{ width: 480, height: 270 },
	),
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-story",
			name: "Story frame",
			category: "frame",
			tags: ["frame", "social"],
			keywords: [
				"story frame",
				"9:16",
				"reel",
				"vertical video",
				"social",
				"phone",
				"tiktok",
			],
		},
		{},
		{ width: 270, height: 480 },
	),
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-panorama",
			name: "Panorama frame",
			category: "frame",
			tags: ["frame", "photo"],
			keywords: [
				"panorama frame",
				"3:1",
				"strip",
				"banner",
				"wide photo",
				"letterbox",
			],
		},
		{},
		{ width: 480, height: 160 },
	),
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-rounded",
			name: "Rounded frame",
			category: "frame",
			tags: ["frame", "photo"],
			keywords: [
				"rounded frame",
				"soft corners",
				"card",
				"image",
				"photo",
				"radius",
			],
		},
		{ radius: 40 },
		{ width: 400, height: 400 },
	),
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-rounded-soft",
			name: "Soft frame",
			category: "frame",
			tags: ["frame", "photo"],
			keywords: [
				"soft frame",
				"squircle",
				"very rounded",
				"app tile",
				"image",
				"photo",
			],
		},
		{ radius: 96 },
		{ width: 400, height: 400 },
	),
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-pill",
			name: "Pill frame",
			category: "frame",
			tags: ["frame", "photo"],
			keywords: [
				"pill frame",
				"capsule",
				"lozenge",
				"banner",
				"image",
				"photo",
				"stadium",
			],
		},
		{ radius: 200 },
		{ width: 480, height: 200 },
	),
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-circle",
			name: "Circle frame",
			category: "frame",
			tags: ["frame", "photo"],
			keywords: [
				"circle frame",
				"avatar",
				"profile",
				"round photo",
				"bubble",
				"headshot",
			],
		},
		{
			shape: { kind: "ellipse" },
			previewD: (size) =>
				`M0 ${size.height / 2}A${size.width / 2} ${size.height / 2} 0 0 1 ${size.width} ${size.height / 2}A${size.width / 2} ${size.height / 2} 0 0 1 0 ${size.height / 2}Z`,
		},
		{ width: 400, height: 400 },
	),
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-oval",
			name: "Oval frame",
			category: "frame",
			tags: ["frame", "photo"],
			keywords: [
				"oval frame",
				"ellipse",
				"cameo",
				"portrait",
				"vignette",
				"round photo",
			],
		},
		{
			shape: { kind: "ellipse" },
			previewD: (size) =>
				`M0 ${size.height / 2}A${size.width / 2} ${size.height / 2} 0 0 1 ${size.width} ${size.height / 2}A${size.width / 2} ${size.height / 2} 0 0 1 0 ${size.height / 2}Z`,
		},
		{ width: 480, height: 320 },
	),
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-triangle",
			name: "Triangle frame",
			category: "frame",
			tags: ["frame", "photo"],
			keywords: [
				"triangle frame",
				"wedge",
				"geometric photo",
				"three",
				"angular",
				"mask",
			],
		},
		{
			shape: { kind: "polygon", sides: 3 },
			previewD: (size) =>
				`M${size.width / 2} 0L${size.width} ${size.height}H0Z`,
		},
		{ width: 400, height: 400 },
	),
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-pentagon",
			name: "Pentagon frame",
			category: "frame",
			tags: ["frame", "photo"],
			keywords: [
				"pentagon frame",
				"geometric photo",
				"five",
				"badge",
				"mask",
				"crest",
			],
		},
		{ shape: { kind: "polygon", sides: 5 } },
		{ width: 400, height: 400 },
	),
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-hexagon",
			name: "Hexagon frame",
			category: "frame",
			tags: ["frame", "photo"],
			keywords: [
				"hexagon frame",
				"honeycomb",
				"geometric photo",
				"six",
				"mask",
				"team photo",
			],
		},
		{ shape: { kind: "polygon", sides: 6 } },
		{ width: 400, height: 400 },
	),
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-octagon",
			name: "Octagon frame",
			category: "frame",
			tags: ["frame", "photo"],
			keywords: [
				"octagon frame",
				"geometric photo",
				"eight",
				"stop",
				"mask",
				"seal",
			],
		},
		{ shape: { kind: "polygon", sides: 8 } },
		{ width: 400, height: 400 },
	),
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-star",
			name: "Star frame",
			category: "frame",
			tags: ["frame", "photo"],
			keywords: [
				"star frame",
				"star mask",
				"photo star",
				"award",
				"favourite",
				"favorite",
			],
		},
		{ shape: { kind: "star", points: 5, innerRadiusRatio: 0.45 } },
		{ width: 400, height: 400 },
	),
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-burst",
			name: "Burst frame",
			category: "frame",
			tags: ["frame", "photo"],
			keywords: [
				"burst frame",
				"scalloped",
				"seal",
				"stamp",
				"flower photo",
				"sunburst",
			],
		},
		{ shape: { kind: "star", points: 16, innerRadiusRatio: 0.84 } },
		{ width: 400, height: 400 },
	),
	frameEntry(
		{
			...OWN_WORK,
			id: "frame-arch",
			name: "Arch frame",
			category: "frame",
			tags: ["frame", "photo"],
			keywords: [
				"arch frame",
				"archway",
				"window",
				"dome photo",
				"portal",
				"tombstone",
			],
		},
		{
			// Generated from the requested size, not stored: a frame is bounds-sized,
			// so a fixed `d` would stop matching its box the moment it is resized.
			shape: {
				kind: "path",
				d: (size) =>
					`M0 ${size.height}V${size.width / 2}A${size.width / 2} ${size.width / 2} 0 0 1 ${size.width} ${size.width / 2}V${size.height}Z`,
			},
			previewD: (size) =>
				`M0 ${size.height}V${size.width / 2}A${size.width / 2} ${size.width / 2} 0 0 1 ${size.width} ${size.width / 2}V${size.height}Z`,
		},
		{ width: 320, height: 420 },
	),
];

// --- stickers ----------------------------------------------------------------

/**
 * Composed graphics: a `group` of primitives, deliberately multi-coloured.
 *
 * `recolor: "multi"` is the honest answer for all of them and is enforced, not
 * asserted: `checkElementEntry` builds each one with a probe fill and requires
 * it to reach at least one part. The part it reaches is the one marked
 * `fill: "inherit"` — the sticker's "primary" surface — while the accents keep
 * their authored colours, which is exactly what `cp3-005`'s contract means by
 * "per-part editing works by selecting the part".
 */
const ACCENT_WARM = "#f97316";
const ACCENT_GOLD = "#facc15";
const ACCENT_ROSE = "#f43f5e";
const ACCENT_SKY = "#38bdf8";
const ACCENT_MINT = "#34d399";
const ACCENT_INK = "#0f172a";
const ACCENT_PAPER = "#ffffff";

const STICKERS: readonly CanvasElementEntry[] = [
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-sale-badge",
			name: "Sale badge",
			category: "sticker",
			tags: ["sticker", "commerce"],
			keywords: [
				"sale badge",
				"discount",
				"offer",
				"promo",
				"starburst",
				"deal",
				"price",
			],
		},
		{
			box: STICKER_BOX,
			previewD:
				"M100 4L120 40L160 30L156 72L196 88L168 120L192 156L150 162L146 196L100 176L54 196L50 162L8 156L32 120L4 88L44 72L40 30L80 40Z",
			parts: [
				{
					kind: "star",
					x: 0,
					y: 0,
					width: 200,
					height: 200,
					points: 12,
					innerRadiusRatio: 0.78,
					fill: "inherit",
				},
				{
					kind: "ellipse",
					x: 28,
					y: 28,
					width: 144,
					height: 144,
					fill: ACCENT_PAPER,
				},
				{
					kind: "star",
					x: 54,
					y: 54,
					width: 92,
					height: 92,
					points: 5,
					innerRadiusRatio: 0.45,
					fill: ACCENT_WARM,
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-new-badge",
			name: "New badge",
			category: "sticker",
			tags: ["sticker", "commerce"],
			keywords: [
				"new badge",
				"label",
				"flash",
				"announcement",
				"launch",
				"tag",
				"just in",
			],
		},
		{
			box: STICKER_BOX,
			previewD: "M8 60H192V140H8Z",
			parts: [
				{
					kind: "rect",
					x: 8,
					y: 60,
					width: 184,
					height: 80,
					radius: 40,
					fill: "inherit",
				},
				{
					kind: "rect",
					x: 22,
					y: 74,
					width: 156,
					height: 52,
					radius: 26,
					fill: ACCENT_PAPER,
				},
				{
					kind: "ellipse",
					x: 36,
					y: 88,
					width: 24,
					height: 24,
					fill: ACCENT_ROSE,
				},
				{
					kind: "ellipse",
					x: 88,
					y: 88,
					width: 24,
					height: 24,
					fill: ACCENT_GOLD,
				},
				{
					kind: "ellipse",
					x: 140,
					y: 88,
					width: 24,
					height: 24,
					fill: ACCENT_SKY,
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-seal",
			name: "Approval seal",
			category: "sticker",
			tags: ["sticker", "celebration"],
			keywords: [
				"seal",
				"stamp",
				"certified",
				"approved",
				"guarantee",
				"quality",
				"rosette",
			],
		},
		{
			box: STICKER_BOX,
			previewD:
				"M100 2A98 98 0 0 1 198 100A98 98 0 0 1 100 198A98 98 0 0 1 2 100A98 98 0 0 1 100 2Z",
			parts: [
				{
					kind: "star",
					x: 0,
					y: 0,
					width: 200,
					height: 200,
					points: 20,
					innerRadiusRatio: 0.9,
					fill: "inherit",
				},
				{
					kind: "ellipse",
					x: 18,
					y: 18,
					width: 164,
					height: 164,
					fill: ACCENT_PAPER,
				},
				{
					kind: "ellipse",
					x: 30,
					y: 30,
					width: 140,
					height: 140,
					fill: "inherit",
				},
				{
					kind: "path",
					x: 58,
					y: 66,
					width: 84,
					height: 68,
					d: "M4 34L28 58L80 6",
					viewBox: { width: 84, height: 64 },
					stroke: ACCENT_PAPER,
					strokeWidth: 12,
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-price-tag",
			name: "Price tag",
			category: "sticker",
			tags: ["sticker", "commerce"],
			keywords: [
				"price tag",
				"label",
				"swing tag",
				"cost",
				"sale",
				"shopping",
				"ticket",
			],
		},
		{
			box: STICKER_BOX,
			previewD: "M96 12H188V104L96 188L12 104Z",
			parts: [
				{
					kind: "rect",
					x: 30,
					y: 30,
					width: 140,
					height: 140,
					radius: 20,
					rotation: 45,
					fill: "inherit",
				},
				{
					kind: "ellipse",
					x: 132,
					y: 44,
					width: 28,
					height: 28,
					fill: ACCENT_PAPER,
				},
				{
					kind: "rect",
					x: 46,
					y: 148,
					width: 60,
					height: 12,
					radius: 6,
					rotation: -45,
					fill: ACCENT_PAPER,
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-ribbon-banner",
			name: "Ribbon banner",
			category: "sticker",
			tags: ["sticker", "celebration"],
			keywords: [
				"ribbon banner",
				"streamer",
				"title bar",
				"header",
				"award ribbon",
				"scroll",
			],
		},
		{
			box: STICKER_BOX,
			previewD: "M0 60H200L176 100L200 140H0L24 100Z",
			parts: [
				{
					kind: "path",
					x: 0,
					y: 60,
					width: 200,
					height: 80,
					d: "M0 0H200L176 40L200 80H0L24 40Z",
					viewBox: { width: 200, height: 80 },
					fill: "inherit",
				},
				{
					kind: "path",
					x: 10,
					y: 74,
					width: 180,
					height: 52,
					d: "M0 0H180L162 26L180 52H0L18 26Z",
					viewBox: { width: 180, height: 52 },
					fill: ACCENT_PAPER,
				},
				{
					kind: "ellipse",
					x: 44,
					y: 88,
					width: 24,
					height: 24,
					fill: ACCENT_GOLD,
				},
				{
					kind: "ellipse",
					x: 132,
					y: 88,
					width: 24,
					height: 24,
					fill: ACCENT_GOLD,
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-speech",
			name: "Speech sticker",
			category: "sticker",
			tags: ["sticker", "communication"],
			keywords: [
				"speech sticker",
				"chat bubble",
				"comment",
				"quote",
				"callout",
				"talk",
				"say",
			],
		},
		{
			box: STICKER_BOX,
			previewD: "M20 20H180V140H90L50 184V140H20Z",
			parts: [
				{
					kind: "path",
					x: 8,
					y: 16,
					width: 184,
					height: 168,
					d: "M24 0H160A24 24 0 0 1 184 24V100A24 24 0 0 1 160 124H88L48 168V124H24A24 24 0 0 1 0 100V24A24 24 0 0 1 24 0Z",
					viewBox: { width: 184, height: 168 },
					fill: "inherit",
				},
				{
					kind: "ellipse",
					x: 52,
					y: 66,
					width: 20,
					height: 20,
					fill: ACCENT_PAPER,
				},
				{
					kind: "ellipse",
					x: 90,
					y: 66,
					width: 20,
					height: 20,
					fill: ACCENT_PAPER,
				},
				{
					kind: "ellipse",
					x: 128,
					y: 66,
					width: 20,
					height: 20,
					fill: ACCENT_PAPER,
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-tape",
			name: "Tape strip",
			category: "sticker",
			tags: ["sticker", "decorative"],
			keywords: [
				"tape strip",
				"washi",
				"masking tape",
				"scrapbook",
				"stick",
				"attach",
				"collage",
			],
		},
		{
			box: STICKER_BOX,
			previewD: "M8 76L192 60V140L8 124Z",
			parts: [
				{
					kind: "path",
					x: 8,
					y: 60,
					width: 184,
					height: 80,
					d: "M0 16L184 0V64L0 80Z",
					viewBox: { width: 184, height: 80 },
					fill: "inherit",
				},
				{
					kind: "rect",
					x: 34,
					y: 88,
					width: 132,
					height: 8,
					radius: 4,
					rotation: -5,
					fill: ACCENT_PAPER,
				},
				{
					kind: "rect",
					x: 34,
					y: 108,
					width: 96,
					height: 8,
					radius: 4,
					rotation: -5,
					fill: ACCENT_PAPER,
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-sparkle-trio",
			name: "Sparkle trio",
			category: "sticker",
			tags: ["sticker", "celebration"],
			keywords: [
				"sparkle trio",
				"sparkles",
				"shine",
				"magic",
				"glitter",
				"stars",
				"ai",
				"twinkle",
			],
		},
		{
			box: STICKER_BOX,
			previewD:
				"M70 20L86 66L132 82L86 98L70 144L54 98L8 82L54 66ZM150 108L160 138L190 148L160 158L150 188L140 158L110 148L140 138Z",
			parts: [
				{
					kind: "star",
					x: 8,
					y: 20,
					width: 124,
					height: 124,
					points: 4,
					innerRadiusRatio: 0.18,
					fill: "inherit",
				},
				{
					kind: "star",
					x: 110,
					y: 108,
					width: 80,
					height: 80,
					points: 4,
					innerRadiusRatio: 0.18,
					fill: ACCENT_GOLD,
				},
				{
					kind: "star",
					x: 132,
					y: 12,
					width: 52,
					height: 52,
					points: 4,
					innerRadiusRatio: 0.18,
					fill: ACCENT_SKY,
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-confetti",
			name: "Confetti",
			category: "sticker",
			tags: ["sticker", "celebration"],
			keywords: [
				"confetti",
				"party",
				"celebration",
				"birthday",
				"festive",
				"scatter",
				"congrats",
			],
		},
		{
			box: STICKER_BOX,
			previewD:
				"M20 24H48V52H20ZM120 16H148V44H120ZM60 100H88V128H60ZM150 96H178V124H150ZM28 152H56V180H28ZM110 156H138V184H110Z",
			parts: [
				{
					kind: "rect",
					x: 20,
					y: 24,
					width: 30,
					height: 14,
					radius: 7,
					rotation: 20,
					fill: "inherit",
				},
				{
					kind: "rect",
					x: 120,
					y: 16,
					width: 30,
					height: 14,
					radius: 7,
					rotation: -25,
					fill: ACCENT_ROSE,
				},
				{
					kind: "rect",
					x: 60,
					y: 100,
					width: 30,
					height: 14,
					radius: 7,
					rotation: 45,
					fill: ACCENT_GOLD,
				},
				{
					kind: "rect",
					x: 150,
					y: 96,
					width: 30,
					height: 14,
					radius: 7,
					rotation: 10,
					fill: ACCENT_MINT,
				},
				{
					kind: "rect",
					x: 28,
					y: 152,
					width: 30,
					height: 14,
					radius: 7,
					rotation: -40,
					fill: ACCENT_SKY,
				},
				{
					kind: "rect",
					x: 110,
					y: 156,
					width: 30,
					height: 14,
					radius: 7,
					rotation: 30,
					fill: "inherit",
				},
				{
					kind: "ellipse",
					x: 88,
					y: 52,
					width: 16,
					height: 16,
					fill: ACCENT_WARM,
				},
				{
					kind: "ellipse",
					x: 168,
					y: 156,
					width: 16,
					height: 16,
					fill: ACCENT_ROSE,
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-dot-cluster",
			name: "Dot cluster",
			category: "sticker",
			tags: ["sticker", "decorative"],
			keywords: [
				"dot cluster",
				"polka dots",
				"halftone",
				"pattern",
				"spots",
				"texture",
				"bubbles",
			],
		},
		{
			box: STICKER_BOX,
			previewD:
				"M40 40A24 24 0 1 1 39.9 40ZM120 30A18 18 0 1 1 119.9 30ZM70 110A20 20 0 1 1 69.9 110ZM150 100A26 26 0 1 1 149.9 100ZM50 170A14 14 0 1 1 49.9 170ZM130 168A16 16 0 1 1 129.9 168Z",
			parts: [
				{
					kind: "ellipse",
					x: 16,
					y: 16,
					width: 48,
					height: 48,
					fill: "inherit",
				},
				{
					kind: "ellipse",
					x: 102,
					y: 12,
					width: 36,
					height: 36,
					fill: ACCENT_SKY,
				},
				{
					kind: "ellipse",
					x: 50,
					y: 90,
					width: 40,
					height: 40,
					fill: ACCENT_MINT,
				},
				{
					kind: "ellipse",
					x: 124,
					y: 74,
					width: 52,
					height: 52,
					fill: "inherit",
				},
				{
					kind: "ellipse",
					x: 36,
					y: 156,
					width: 28,
					height: 28,
					fill: ACCENT_GOLD,
				},
				{
					kind: "ellipse",
					x: 114,
					y: 152,
					width: 32,
					height: 32,
					fill: ACCENT_ROSE,
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-arrow-pointer",
			name: "Arrow sticker",
			category: "sticker",
			tags: ["sticker", "arrow"],
			keywords: [
				"arrow sticker",
				"look here",
				"pointer",
				"annotation",
				"callout",
				"this way",
			],
		},
		{
			box: STICKER_BOX,
			previewD: "M16 150C60 60 130 30 184 52L150 20L184 52L152 88Z",
			parts: [
				{
					kind: "path",
					x: 12,
					y: 40,
					width: 176,
					height: 120,
					d: "M4 116C48 26 118 -4 172 18",
					viewBox: { width: 176, height: 120 },
					stroke: ACCENT_INK,
					strokeWidth: 10,
				},
				{
					kind: "polygon",
					x: 140,
					y: 24,
					width: 56,
					height: 56,
					sides: 3,
					rotation: 118,
					fill: "inherit",
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-blob-duo",
			name: "Blob duo",
			category: "sticker",
			tags: ["sticker", "organic"],
			keywords: [
				"blob duo",
				"organic shapes",
				"abstract",
				"background",
				"splat",
				"freeform",
			],
		},
		{
			box: STICKER_BOX,
			previewD:
				"M124 12C164 20 196 52 192 96C188 140 156 184 108 192C60 200 16 168 10 120C4 72 28 28 68 14C90 6 104 8 124 12Z",
			parts: [
				{
					kind: "path",
					x: 4,
					y: 8,
					width: 192,
					height: 192,
					d: "M120 4C160 12 192 44 188 88C184 132 152 176 104 184C56 192 12 160 6 112C0 64 24 20 64 6C86 -2 100 0 120 4Z",
					viewBox: { width: 192, height: 192 },
					fill: "inherit",
				},
				{
					kind: "path",
					x: 74,
					y: 82,
					width: 108,
					height: 100,
					d: "M64 2C88 8 106 26 104 50C102 74 82 96 54 98C26 100 4 82 2 58C0 34 16 10 40 4C50 1 56 0 64 2Z",
					viewBox: { width: 108, height: 100 },
					fill: ACCENT_MINT,
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-circle-stack",
			name: "Circle stack",
			category: "sticker",
			tags: ["sticker", "decorative"],
			keywords: [
				"circle stack",
				"target",
				"rings",
				"concentric",
				"bullseye",
				"layers",
				"orbit",
			],
		},
		{
			box: STICKER_BOX,
			previewD: "M100 4A96 96 0 1 1 99.9 4ZM100 52A48 48 0 1 0 100.1 52Z",
			parts: [
				{
					kind: "ellipse",
					x: 4,
					y: 4,
					width: 192,
					height: 192,
					fill: "inherit",
				},
				{
					kind: "ellipse",
					x: 34,
					y: 34,
					width: 132,
					height: 132,
					fill: ACCENT_PAPER,
				},
				{
					kind: "ellipse",
					x: 60,
					y: 60,
					width: 80,
					height: 80,
					fill: ACCENT_ROSE,
				},
				{
					kind: "ellipse",
					x: 84,
					y: 84,
					width: 32,
					height: 32,
					fill: ACCENT_PAPER,
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-check-badge",
			name: "Verified badge",
			category: "sticker",
			tags: ["sticker", "status"],
			keywords: [
				"verified badge",
				"check",
				"approved",
				"done",
				"trusted",
				"tick",
				"confirmed",
			],
		},
		{
			box: STICKER_BOX,
			previewD:
				"M100 4L128 24L162 20L174 52L204 70L192 100L204 130L174 148L162 180L128 176L100 196L72 176L38 180L26 148L-4 130L8 100L-4 70L26 52L38 20L72 24Z",
			parts: [
				{
					kind: "star",
					x: 0,
					y: 0,
					width: 200,
					height: 200,
					points: 8,
					innerRadiusRatio: 0.86,
					fill: "inherit",
				},
				{
					kind: "path",
					x: 52,
					y: 66,
					width: 96,
					height: 72,
					d: "M4 38L34 66L92 6",
					viewBox: { width: 96, height: 72 },
					stroke: ACCENT_PAPER,
					strokeWidth: 14,
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-heart-burst",
			name: "Heart burst",
			category: "sticker",
			tags: ["sticker", "social"],
			keywords: [
				"heart burst",
				"love",
				"like",
				"reaction",
				"favourite",
				"favorite",
				"pop",
			],
		},
		{
			box: STICKER_BOX,
			previewD:
				"M100 176C100 176 20 128 20 74C20 42 44 20 70 20C86 20 96 30 100 40C104 30 114 20 130 20C156 20 180 42 180 74C180 128 100 176 100 176Z",
			parts: [
				{
					kind: "star",
					x: 6,
					y: 6,
					width: 188,
					height: 188,
					points: 10,
					innerRadiusRatio: 0.72,
					fill: ACCENT_GOLD,
				},
				{
					kind: "path",
					x: 30,
					y: 34,
					width: 140,
					height: 132,
					d: "M50 96C50 96 6 68 6 36C6 18 20 6 34 6C42 6 48 11 50 16C52 11 58 6 66 6C80 6 94 18 94 36C94 68 50 96 50 96Z",
					viewBox: { width: 100, height: 100 },
					fill: "inherit",
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-star-rating",
			name: "Star rating",
			category: "sticker",
			tags: ["sticker", "social"],
			keywords: [
				"star rating",
				"five stars",
				"review",
				"score",
				"testimonial",
				"rate",
				"feedback",
			],
		},
		{
			box: { width: 200, height: 60 },
			previewD: "M20 4L26 20L42 22L30 34L34 50L20 42L6 50L10 34L-2 22L14 20Z",
			parts: [
				{
					kind: "star",
					x: 0,
					y: 6,
					width: 36,
					height: 36,
					points: 5,
					innerRadiusRatio: 0.45,
					fill: "inherit",
				},
				{
					kind: "star",
					x: 41,
					y: 6,
					width: 36,
					height: 36,
					points: 5,
					innerRadiusRatio: 0.45,
					fill: "inherit",
				},
				{
					kind: "star",
					x: 82,
					y: 6,
					width: 36,
					height: 36,
					points: 5,
					innerRadiusRatio: 0.45,
					fill: "inherit",
				},
				{
					kind: "star",
					x: 123,
					y: 6,
					width: 36,
					height: 36,
					points: 5,
					innerRadiusRatio: 0.45,
					fill: "inherit",
				},
				{
					kind: "star",
					x: 164,
					y: 6,
					width: 36,
					height: 36,
					points: 5,
					innerRadiusRatio: 0.45,
					fill: ACCENT_GOLD,
				},
			],
		},
		{ width: 320, height: 96 },
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-quote",
			name: "Quote marks",
			category: "sticker",
			tags: ["sticker", "typography"],
			keywords: [
				"quote marks",
				"quotation",
				"testimonial",
				"citation",
				"speech marks",
				"blockquote",
			],
		},
		{
			box: STICKER_BOX,
			previewD:
				"M20 40H80V100C80 140 56 164 20 172V140C40 132 52 120 52 100H20ZM120 40H180V100C180 140 156 164 120 172V140C140 132 152 120 152 100H120Z",
			parts: [
				{
					kind: "path",
					x: 16,
					y: 40,
					width: 72,
					height: 132,
					d: "M0 0H60V60C60 100 36 124 0 132V100C20 92 32 80 32 60H0Z",
					viewBox: { width: 60, height: 132 },
					fill: "inherit",
				},
				{
					kind: "path",
					x: 112,
					y: 40,
					width: 72,
					height: 132,
					d: "M0 0H60V60C60 100 36 124 0 132V100C20 92 32 80 32 60H0Z",
					viewBox: { width: 60, height: 132 },
					fill: ACCENT_SKY,
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-corner-brackets",
			name: "Corner brackets",
			category: "sticker",
			tags: ["sticker", "decorative"],
			keywords: [
				"corner brackets",
				"crop marks",
				"viewfinder",
				"focus",
				"framing",
				"target",
			],
		},
		{
			box: STICKER_BOX,
			previewD: "M8 60V8H60M140 8H192V60M192 140V192H140M60 192H8V140",
			parts: [
				{
					kind: "path",
					x: 8,
					y: 8,
					width: 60,
					height: 60,
					d: "M0 52V0H52",
					viewBox: { width: 52, height: 52 },
					stroke: ACCENT_INK,
					strokeWidth: 8,
				},
				{
					kind: "path",
					x: 132,
					y: 8,
					width: 60,
					height: 60,
					d: "M0 0H52V52",
					viewBox: { width: 52, height: 52 },
					stroke: ACCENT_INK,
					strokeWidth: 8,
				},
				{
					kind: "path",
					x: 132,
					y: 132,
					width: 60,
					height: 60,
					d: "M52 0V52H0",
					viewBox: { width: 52, height: 52 },
					stroke: ACCENT_INK,
					strokeWidth: 8,
				},
				{
					kind: "path",
					x: 8,
					y: 132,
					width: 60,
					height: 60,
					d: "M52 52H0V0",
					viewBox: { width: 52, height: 52 },
					stroke: ACCENT_INK,
					strokeWidth: 8,
				},
				{
					kind: "ellipse",
					x: 84,
					y: 84,
					width: 32,
					height: 32,
					fill: "inherit",
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-pennant",
			name: "Pennant flag",
			category: "sticker",
			tags: ["sticker", "celebration"],
			keywords: [
				"pennant flag",
				"bunting",
				"party flag",
				"banner",
				"triangle flag",
				"festival",
			],
		},
		{
			box: STICKER_BOX,
			previewD: "M28 20H180L120 96L180 172H28Z",
			parts: [
				{
					kind: "path",
					x: 28,
					y: 20,
					width: 152,
					height: 152,
					d: "M0 0H152L92 76L152 152H0Z",
					viewBox: { width: 152, height: 152 },
					fill: "inherit",
				},
				{
					kind: "rect",
					x: 16,
					y: 12,
					width: 12,
					height: 176,
					radius: 6,
					fill: ACCENT_INK,
				},
				{
					kind: "ellipse",
					x: 56,
					y: 82,
					width: 28,
					height: 28,
					fill: ACCENT_PAPER,
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-bubble-trio",
			name: "Bubble trio",
			category: "sticker",
			tags: ["sticker", "communication"],
			keywords: [
				"bubble trio",
				"conversation",
				"chat group",
				"comments",
				"discussion",
				"thread",
			],
		},
		{
			box: STICKER_BOX,
			previewD:
				"M8 24H124V96H60L36 124V96H8ZM76 108H192V180H128L104 208V180H76Z",
			parts: [
				{
					kind: "path",
					x: 8,
					y: 24,
					width: 116,
					height: 100,
					d: "M16 0H100A16 16 0 0 1 116 16V56A16 16 0 0 1 100 72H52L28 100V72H16A16 16 0 0 1 0 56V16A16 16 0 0 1 16 0Z",
					viewBox: { width: 116, height: 100 },
					fill: "inherit",
				},
				{
					kind: "path",
					x: 76,
					y: 100,
					width: 116,
					height: 100,
					d: "M16 0H100A16 16 0 0 1 116 16V56A16 16 0 0 1 100 72H52L28 100V72H16A16 16 0 0 1 0 56V16A16 16 0 0 1 16 0Z",
					viewBox: { width: 116, height: 100 },
					fill: ACCENT_SKY,
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-lightning-flash",
			name: "Flash sticker",
			category: "sticker",
			tags: ["sticker", "celebration"],
			keywords: [
				"flash sticker",
				"lightning",
				"bolt",
				"energy",
				"power up",
				"zap",
				"fast",
				"boost",
			],
		},
		{
			box: STICKER_BOX,
			previewD: "M112 4L28 116H88L76 196L172 80H112Z",
			parts: [
				{
					kind: "ellipse",
					x: 10,
					y: 10,
					width: 180,
					height: 180,
					fill: ACCENT_GOLD,
				},
				{
					kind: "path",
					x: 50,
					y: 24,
					width: 100,
					height: 152,
					d: "M56 2L14 58H44L38 98L86 40H54Z",
					viewBox: { width: 100, height: 100 },
					fill: "inherit",
				},
			],
		},
		STICKER_SIZE,
	),
	stickerEntry(
		{
			...OWN_WORK,
			id: "sticker-arch-plate",
			name: "Arch plate",
			category: "sticker",
			tags: ["sticker", "decorative"],
			keywords: [
				"arch plate",
				"backdrop",
				"panel",
				"podium",
				"label plate",
				"window",
				"tombstone",
			],
		},
		{
			box: STICKER_BOX,
			previewD: "M12 192V100A88 88 0 0 1 188 100V192Z",
			parts: [
				{
					kind: "path",
					x: 12,
					y: 12,
					width: 176,
					height: 180,
					d: "M0 180V88A88 88 0 0 1 176 88V180Z",
					viewBox: { width: 176, height: 180 },
					fill: "inherit",
				},
				{
					kind: "path",
					x: 34,
					y: 34,
					width: 132,
					height: 136,
					d: "M0 136V66A66 66 0 0 1 132 66V136Z",
					viewBox: { width: 132, height: 136 },
					fill: ACCENT_PAPER,
				},
				{
					kind: "ellipse",
					x: 84,
					y: 74,
					width: 32,
					height: 32,
					fill: ACCENT_WARM,
				},
			],
		},
		STICKER_SIZE,
	),
];

/** Everything in this module, in panel order: shapes, lines, frames, stickers. */
export const SHAPE_ENTRIES: readonly CanvasElementEntry[] = [
	...PRIMITIVE_SHAPES,
	...PATH_SHAPES,
];
export const LINE_ENTRIES: readonly CanvasElementEntry[] = LINES;
export const FRAME_ENTRIES: readonly CanvasElementEntry[] = FRAMES;
export const STICKER_ENTRIES: readonly CanvasElementEntry[] = STICKERS;

/**
 * The licensing record for everything in this module. Shaped exactly like the
 * vendored sets' records so `cp6-006` reads ONE list, not "the upstream ones
 * plus whatever is implicit about our own".
 */
export const OWN_WORK_ATTRIBUTION = {
	setName: "AnvilKit Canvas — shapes, lines, frames and stickers",
	license: MIT,
	copyright: "Copyright (c) 2026 Ancyloce",
	upstreamUrl: OWN_WORK.upstreamUrl,
	verifiedFrom: "Original geometry authored in this package (see LICENSE)",
} as const;
