export {
	CanvasActivityError,
	type CanvasActivityEventBase,
	type CanvasActivityEvent,
	type CanvasActivitySink,
	type CanvasCollaborationActivityEvent,
	type CanvasCollaborationRecoveryCode,
	type CanvasCommentActivityEvent,
	type CanvasMemoryActivitySink,
	type CanvasRoleActivityEvent,
	type CanvasShareActivityEvent,
	type RecordCanvasRoleChangeInput,
	assertCanvasActivityEvent,
	createMemoryCanvasActivitySink,
	emitCanvasActivity,
	recordCanvasRoleChange,
} from "./activity-events.js";
export {
	CANVAS_AUTHORIZATION_ACTIONS,
	CANVAS_COLLABORATION_ROLES,
	CANVAS_ROLE_PERMISSIONS,
	CanvasAuthorizationError,
	type CanvasAuthorizationAction,
	type CanvasAuthorizationDecision,
	type CanvasAuthorizationDecisionCode,
	type CanvasAuthorizationDeny,
	type CanvasAuthorizationGrant,
	type CanvasAuthorizationResource,
	type CanvasAuthorizationScope,
	type CanvasAuthorizationScopeKind,
	type CanvasAuthorizationSession,
	type CanvasCollaborationRole,
	type ResolveCanvasAuthorizationOptions,
	assertCanvasAuthorized,
	assertCanvasSessionAuthorized,
	canvasDocumentAuthorizationResource,
	isCanvasDocumentWriteAllowed,
	isCanvasActionAllowedForRole,
	resolveCanvasAuthorization,
	resolveCanvasSessionAuthorization,
} from "./authorization.js";
export {
	CanvasShareLinkError,
	type CanvasClipboardTextWriter,
	type CanvasShareLinkAccessCode,
	type CanvasShareLinkAccessDecision,
	type CanvasShareLinkAccessRequest,
	type CanvasShareLinkCreated,
	type CanvasShareLinkErrorCode,
	type CanvasShareLinkHostPolicy,
	type CanvasShareLinkIdentity,
	type CanvasShareLinkProvider,
	type CanvasShareLinkRecord,
	type CanvasShareLinkRestrictions,
	type CanvasShareLinkRole,
	type CanvasShareLinkStatus,
	type CreateCanvasShareLinkRequest,
	type CreateAuthorizedCanvasShareLinkProviderOptions,
	type CreateMemoryCanvasShareLinkProviderOptions,
	copyCanvasShareLink,
	createAuthorizedCanvasShareLinkProvider,
	createMemoryCanvasShareLinkProvider,
} from "./share-links.js";
